#!/bin/sh

#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#    MA 02110-1301 USA.
# 
# Author: Sergey Senozhatsky, 2012
#

CPUNR=0
CORENR=0
LOOP=0
SLEEP=0
CLEAR=0
TEMP_UNIT="\u00b0C"

function usage {
	echo "Usage: coretemp-sensors [-t timeout] [-c]"
	echo -e "\t -t: loop mode with timeout seconds sleep"
	echo -e "\t -c: clear screen before reporting"
	exit 1
}

function clr {
	if [ ${CLEAR} -eq 1 ]; then
		clear
	fi
}

function init {
	CPUNR=`cat /proc/cpuinfo | grep -i -c GenuineIntel`
	if [ ${CPUNR} -lt 1 ]; then
		echo "No GenuineIntel vendor_id CPU found"
		exit 1
	fi

	CORENR=`cat /proc/cpuinfo | grep -i 'cpu cores' | sort -u | sed -e 's/[[:alpha:]:]//g'`

	CPUFAMILY=`cat /proc/cpuinfo | grep -i 'cpu family' | sort -u | sed -e 's/[[:alpha:]:]//g'`
	if [ ${CPUFAMILY} -lt 6 ]; then
		echo "CPU family >= 6 required"
		exit 1
	fi
}

function report_coretemp {
	#
	# Coretemp map the attr number to core id of the CPU.
	# The attr number is always core id + 2.
	#

	cd /sys/devices/platform/coretemp.0
	echo -e "driver: `cat name`"

	CID=0
	for CID in $(seq $CORENR); do
		let CID=$CID*2
		LABEL=`cat temp${CID}_label`
		INPUT=`cat temp${CID}_input`
		MAX=`cat temp${CID}_max`
		CRIT=`cat temp${CID}_crit`
	
		let INPUT=INPUT/1000;
		let MAX=MAX/1000;
		let CRIT=CRIT/1000;
	
		let MAX_THRESHOLD13=$MAX-13*$MAX/100;
		let MAX_THRESHOLD7=$MAX-7*$MAX/100;

		SPC="  "
		if [ ${INPUT} -gt 99 ]; then
			SPC=" "
		fi

		INPUT_STR="\t ${INPUT}${TEMP_UNIT}${SPC}"
		if [ ${INPUT} -gt ${MAX} ]; then
			INPUT_STR="\e[01;41m\t ${INPUT}${TEMP_UNIT}${SPC}\e[00m"
		elif [ ${INPUT} -gt ${MAX_THRESHOLD7} ]; then
			INPUT_STR="\e[01;45m\t ${INPUT}${TEMP_UNIT}${SPC}\e[00m"
		elif [ ${INPUT} -gt ${MAX_THRESHOLD13} ]; then
			INPUT_STR="\e[01;43m\t ${INPUT}${TEMP_UNIT}${SPC}\e[00m"
		fi
		MAX_STR=" ${MAX}${TEMP_UNIT} "
		CRIT_STR=" ${CRIT}${TEMP_UNIT}"

		echo -e "$LABEL: $INPUT_STR (max =+$MAX_STR crit =+$CRIT_STR)"
	done
}

init

while getopts t:ch option; do
	case "${option}"
	in
		t) let LOOP=1; let SLEEP=${OPTARG};;
		c) let CLEAR=1;;
		h) usage
		exit 1;;
	esac
done

if [ ${LOOP} -eq 0 ]; then
	report_coretemp
	exit 0
fi

while [ ${LOOP} -eq 1 ]; do
	clr
	report_coretemp
	sleep $SLEEP
done

